### PR TITLE
Tickets.php updates

### PR DESCRIPTION
**Pull request by wrongecho**
- General reformatting
- Main ticket view defaults to open tickets only
- Adjusted logic for open tickets to include tickets in working/on-hold states.
- Added filter to advanced search for ticket state
- Removed query string for the total/open/closed counts/filters
- Hyperlinked the unassigned tickets button.
  - Future work here would be to allow tickets to be filtered by assignee. 
    - This is currently a challenge as would require even more if statements for the $sql query, or a way of filtering for ticket_assigned_to but also allowing it to be anything (without using LIKE to avoid tickets assigned to user id 22 showing for user 2)

### CODE REVIEW

**Comment by johnnyq** [comment]
Super!!! Reeling this one in Thanks @wrongecho

**Comment by aftechro** [comment]
hey guys, i got a developer on fiver looking in to tickets for me :D not sure how fast he will do the work, but i`ll let you know once i have more from him :d

Anyway, nice job @wrongecho

**Comment by johnnyq** [comment]
That's super nice @aftechro 
Fiver looks interesting I have never used it before. I'm guessing its a bunch of developers for hire. Let us know what they say. All help is much appreciated, thanks @aftechro

**Comment by aftechro** [comment]
yep, fiver is a freelance platform you can hire developers which have time and knowledge. will keep you posted

**Comment by wrongecho** [comment]
Hey @aftechro, did you already start with paying someone on Fiverr? Happy to look into this with you if you haven't started yet.

**Comment by aftechro** [comment]
Yep, already done it. I'll upload his work later on today in about few hours. Just need to change few UI aspects

**Comment by wrongecho** [comment]
Oh, I see - that was very quick. Looking forward to seeing it!

**Comment by aftechro** [comment]
@wrongecho can you jump on discord please? need your help :d

**Pull request merged**
