### PR TITLE
Services

### PR DESCRIPTION
**Pull request by wrongecho**
#322 

WIP

### CODE REVIEW

**Comment by johnnyq** [comment]
Oh this is going to be good, Excellent work. I cant wait to try this. Thank you!!

**Comment by Wikiphil** [comment]
How I can test these changes? Is "git pull" bring the changes in my lab?

**Comment by wrongecho** [comment]
@Wikiphil, this is still a work in progress so isn't fully functioning yet. When it's (more) finished and merged into the code you can use git pull to get it.

If you want to play around with it before then, you can follow something like https://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo

**Comment by wrongecho** [comment]
This should be good for initial review.
Left out some features for now (linking: certificates, backup, services, urls, files) for various reasons but these can be discussed further and added at a later date.
Let me know your thoughts?

**Comment by johnnyq** [comment]
Super! I'll go ahead and merge this in and start testing Thanks @wrongecho

**Pull request merged**
