### PR TITLE
Ticket improvements

### PR DESCRIPTION
**Pull request by wrongecho**
Mainly from #225 / #221 (not 255, oops!).
- Add db structure for customer feedback (I like the idea of Good/OK/Bad smiley faces)
- Add support for time tracking
  - You may want to move the JS into a separate file
- Add support for public/internal updates (I've used the existing "Email update to client", hope that's okay :) 
  - I've adjusted the internal notes card background, not sure if you'll like the colour though.
- Small edit to setup.php

What are your thoughts on moving the ticket reply box above the ticket comments? After you get about 5/6 replies you really have to start to scroll. Would make sense as the latest replies are at the top as well.

### CODE REVIEW

**Comment by johnnyq** [comment]
- I do too, its simple
- We have an app.js file for this but thats really global I dont see any problem including it directly into the php file
- That sounds fine, ill take a look at the color after i Merge
- nice wording

I agree I actually had the ticket reply box on top of the comments at one point, but I agree I think moving it back will be ideal especially as more commend are posted or we can move the whole ticket reply to a modal which would make the whole ticket details page less cluttered, how do you feel about reply using modal instead?

Thank you

**Comment by wrongecho** [comment]
Thank you! :)

In terms of the ticket reply, I'd personally prefer just keeping it on the page rather than in a separate popup, just at the top. I think it makes it much easier to work with everything on the same page, can just scroll down a little and see the last update. 
We could probably do with adjusting the default height of the reply box - or showing/hiding it with javascript?

I did have a couple of other questions for you please:
- Documentation: this is currently on the itflow site, is there a way to contribute to / add general documentation?
- Roadmap: Besides the issues open here, do you have a general idea of how you want this to progress - and the structure for that progression (via issues/a kanban, etc)? 
  - I just ask as I'm basically adding/adjusting things I like that are in other software. Unless you're essentially open to adding almost anything that might be useful/helpful on the fly, or would you prefer issues are raised first? I'm fairly new to contributing to open source stuff, so just trying to do so in the most efficient way :)
- License: Have you considered adding a project license like GNU GPLv3? This just makes it "official" that this project is open-source, etc. 
  - https://choosealicense.com/licenses/gpl-3.0/

**Comment by johnnyq** [comment]
I agree with you there, lets keep it the way it is for now I have it above the ticket replies

1. Register yourself as a user on ITflow and ill promote you to admin. to make changes to the CMS
2. No Roadmap really just really trying to make everything existing pretty solid and bug free but new feature are welcome, but still keeping it simple and minimal.
3. GNU GPLv3 is what this project is, Maybe adding it to the readme would be good

Don't sell yourself short you had be convinced you were a pro

Also send me you contact details you can use the contact form on pittpc.com.

Thank again

**Comment by wrongecho** [comment]
Reply box definitely looks better at the top. I like what you've done with the replies card outline too, looks very neat but still easy to see what notes are public/internal.
Hahaha, thank you for the compliment :)
I've made an account and submitted the form at pittpc.com. 

Cheers!

**Pull request merged**
