### PR TITLE
Ticket.php

### PR DESCRIPTION
**Pull request by aftechro**
- added related ticket for same contact
- added total time worked on the ticket (sum of total of each reply time)
- top card-bar color

### CODE REVIEW

**Comment by johnnyq** [comment]
Fantastic addition I really like the black Card Border makes them stand out. I love the ticket stats for the selected contact as you can see how many tickets that contacts has. Nice Work @aftechro!!

**Comment by aftechro** [comment]
Glad you like it! Took a while to get the SQL queries to work, but once i figure it out, all great :D still more things to be done, but with baby steps and all the help from everyone involved we can get awesome things :D

**Comment by aftechro** [comment]
hmmm, total time worked on ticket, does it work for you?

**Comment by aftechro** [comment]
Also, any chance you could add the url for each type of ticket, when click on the number attached, open ticket=status for the contact: Show all open ticket, closed ticket and total tickets

**Comment by wrongecho** [comment]
> hmmm, total time worked on ticket, does it work for you?

Looking good!! 
time-worked

**Comment by aftechro** [comment]
So then is just me and my mysql server, have to move it on mariadb some day 😁
Thanks for confirming @wrongecho

**Pull request merged**
